// Package order provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package order

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostCustomerCostumerIDOrdersWithBody request with any body
	PostCustomerCostumerIDOrdersWithBody(ctx context.Context, costumerID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostCustomerCostumerIDOrders(ctx context.Context, costumerID string, body PostCustomerCostumerIDOrdersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCustomerCostumerIDOrdersOrderID request
	GetCustomerCostumerIDOrdersOrderID(ctx context.Context, costumerID string, orderID string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostCustomerCostumerIDOrdersWithBody(ctx context.Context, costumerID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCustomerCostumerIDOrdersRequestWithBody(c.Server, costumerID, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostCustomerCostumerIDOrders(ctx context.Context, costumerID string, body PostCustomerCostumerIDOrdersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCustomerCostumerIDOrdersRequest(c.Server, costumerID, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCustomerCostumerIDOrdersOrderID(ctx context.Context, costumerID string, orderID string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCustomerCostumerIDOrdersOrderIDRequest(c.Server, costumerID, orderID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostCustomerCostumerIDOrdersRequest calls the generic PostCustomerCostumerIDOrders builder with application/json body
func NewPostCustomerCostumerIDOrdersRequest(server string, costumerID string, body PostCustomerCostumerIDOrdersJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostCustomerCostumerIDOrdersRequestWithBody(server, costumerID, "application/json", bodyReader)
}

// NewPostCustomerCostumerIDOrdersRequestWithBody generates requests for PostCustomerCostumerIDOrders with any type of body
func NewPostCustomerCostumerIDOrdersRequestWithBody(server string, costumerID string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "costumerID", runtime.ParamLocationPath, costumerID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/customer/%s/orders", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetCustomerCostumerIDOrdersOrderIDRequest generates requests for GetCustomerCostumerIDOrdersOrderID
func NewGetCustomerCostumerIDOrdersOrderIDRequest(server string, costumerID string, orderID string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "costumerID", runtime.ParamLocationPath, costumerID)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "orderID", runtime.ParamLocationPath, orderID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/customer/%s/orders/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostCustomerCostumerIDOrdersWithBodyWithResponse request with any body
	PostCustomerCostumerIDOrdersWithBodyWithResponse(ctx context.Context, costumerID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCustomerCostumerIDOrdersResponse, error)

	PostCustomerCostumerIDOrdersWithResponse(ctx context.Context, costumerID string, body PostCustomerCostumerIDOrdersJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCustomerCostumerIDOrdersResponse, error)

	// GetCustomerCostumerIDOrdersOrderIDWithResponse request
	GetCustomerCostumerIDOrdersOrderIDWithResponse(ctx context.Context, costumerID string, orderID string, reqEditors ...RequestEditorFn) (*GetCustomerCostumerIDOrdersOrderIDResponse, error)
}

type PostCustomerCostumerIDOrdersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Order
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r PostCustomerCostumerIDOrdersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostCustomerCostumerIDOrdersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetCustomerCostumerIDOrdersOrderIDResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Order
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r GetCustomerCostumerIDOrdersOrderIDResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCustomerCostumerIDOrdersOrderIDResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostCustomerCostumerIDOrdersWithBodyWithResponse request with arbitrary body returning *PostCustomerCostumerIDOrdersResponse
func (c *ClientWithResponses) PostCustomerCostumerIDOrdersWithBodyWithResponse(ctx context.Context, costumerID string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCustomerCostumerIDOrdersResponse, error) {
	rsp, err := c.PostCustomerCostumerIDOrdersWithBody(ctx, costumerID, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCustomerCostumerIDOrdersResponse(rsp)
}

func (c *ClientWithResponses) PostCustomerCostumerIDOrdersWithResponse(ctx context.Context, costumerID string, body PostCustomerCostumerIDOrdersJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCustomerCostumerIDOrdersResponse, error) {
	rsp, err := c.PostCustomerCostumerIDOrders(ctx, costumerID, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCustomerCostumerIDOrdersResponse(rsp)
}

// GetCustomerCostumerIDOrdersOrderIDWithResponse request returning *GetCustomerCostumerIDOrdersOrderIDResponse
func (c *ClientWithResponses) GetCustomerCostumerIDOrdersOrderIDWithResponse(ctx context.Context, costumerID string, orderID string, reqEditors ...RequestEditorFn) (*GetCustomerCostumerIDOrdersOrderIDResponse, error) {
	rsp, err := c.GetCustomerCostumerIDOrdersOrderID(ctx, costumerID, orderID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCustomerCostumerIDOrdersOrderIDResponse(rsp)
}

// ParsePostCustomerCostumerIDOrdersResponse parses an HTTP response from a PostCustomerCostumerIDOrdersWithResponse call
func ParsePostCustomerCostumerIDOrdersResponse(rsp *http.Response) (*PostCustomerCostumerIDOrdersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostCustomerCostumerIDOrdersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Order
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetCustomerCostumerIDOrdersOrderIDResponse parses an HTTP response from a GetCustomerCostumerIDOrdersOrderIDWithResponse call
func ParseGetCustomerCostumerIDOrdersOrderIDResponse(rsp *http.Response) (*GetCustomerCostumerIDOrdersOrderIDResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCustomerCostumerIDOrdersOrderIDResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Order
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
